{
 "title": "MTConnect Fleet",
 "time": { "from": "2023-04-09T19:28:21.556Z", "to": "2023-04-09T19:48:21.556Z" },
 "panels": [
  {
   "title": "Fleet Availability (%)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "dashboard_data.collection_8.find({}).sort({RecordNumber: -1}).limit(1)",
     "query": "dashboard_data.collection_8.find({}).sort({RecordNumber: -1}).limit(1)"
    }
   ]
  },
  {
   "title": "Production Level (%)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "dashboard_data.collection_8.find({}).sort({RecordNumber: -1}).limit(1)",
     "query": "dashboard_data.collection_8.find({}).sort({RecordNumber: -1}).limit(1)"
    }
   ]
  },
  {
   "title": "Tormach-PCNC1100: Rotational Velocity (Last 2 Minutes)",
   "type": "xychart",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "targets": [
    {
     "parsedQuery": "dashboard_data.collection_8.find({}).sort({RecordNumber: -1}).limit(120)",
     "query": "dashboard_data.collection_8.find({}).sort({RecordNumber: -1}).limit(120)"
    }
   ]
  },
  {
   "title": "Tormach PCNC-1100: Emergency Stop Monitor",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "parsedQuery": "dashboard_data.collection_8.find({}).sort({RecordNumber: -1}).limit(300)",
     "query": "dashboard_data.collection_8.find({}).sort({RecordNumber: -1}).limit(300)"
    }
   ]
  },
  {
   "title": "Fleet Availability",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "parsedQuery": "dashboard_data.collection_8.find({}, {\"Tormach-PCNC1100.Device.Events.Availability.#text\":1,\"Haas.Device.Events.Availability.#text\":1,\"UR5.Device.Events.Availability.#text\":1,\"Tormach_2.Device.Events.Availability.#text\":1,\"Tormach_3.Device.Events.Availability.#text\":1,\"Tormach_4.Device.Events.Availability.#text\":1,\"Tormach_5.Device.Events.Availability.#text\":1,\"Tormach_6.Device.Events.Availability.#text\":1,\"_id\":0}).sort({RecordNumber: -1}).limit(1)",
     "query": "dashboard_data.collection_8.find({}, {\n  'Tormach-PCNC1100.Device.Events.Availability.#text': 1,\n  'Haas.Device.Events.Availability.#text': 1,\n  'UR5.Device.Events.Availability.#text': 1,\n  'Tormach_2.Device.Events.Availability.#text': 1,\n  'Tormach_3.Device.Events.Availability.#text': 1,\n  'Tormach_4.Device.Events.Availability.#text': 1,\n  'Tormach_5.Device.Events.Availability.#text': 1,\n  'Tormach_6.Device.Events.Availability.#text': 1,\n  '_id': 0\n}).sort({RecordNumber: -1}).limit(1)"
    }
   ]
  },
  {
   "title": "Fleet Production Snapshot",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "parsedQuery": "dashboard_data.collection_8.find({}, {\"Tormach-PCNC1100.Path.Events.Execution.#text\":1,\"Haas.Path.Events.Execution.#text\":1,\"UR5.Path.Events.Execution.#text\":1,\"Tormach_2.Path.Events.Execution.#text\":1,\"Tormach_3.Path.Events.Execution.#text\":1,\"Tormach_4.Path.Events.Execution.#text\":1,\"Tormach_5.Path.Events.Execution.#text\":1,\"Tormach_6.Path.Events.Execution.#text\":1,\"_id\":0}).sort({RecordNumber: -1}).limit(1)",
     "query": "dashboard_data.collection_8.find({}, {\n  'Tormach-PCNC1100.Path.Events.Execution.#text': 1,\n  'Haas.Path.Events.Execution.#text': 1,\n  'UR5.Path.Events.Execution.#text': 1,\n  'Tormach_2.Path.Events.Execution.#text': 1,\n  'Tormach_3.Path.Events.Execution.#text': 1,\n  'Tormach_4.Path.Events.Execution.#text': 1,\n  'Tormach_5.Path.Events.Execution.#text': 1,\n  'Tormach_6.Path.Events.Execution.#text': 1,\n  '_id': 0\n}).sort({RecordNumber: -1}).limit(1)"
    }
   ]
  },
  {
   "title": "Tormach PCNC-1100: Operating Status History",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 13 },
   "targets": [
    {
     "parsedQuery": "dashboard_data.collection_8.find({}, {\"time\":\"$MTConnectStreams.Header.@creationTime\",\"Tormach-PCNC1100.Path.Events.Execution.#text\":1,\"_id\":0}).sort({RecordNumber: -1}).limit(120)",
     "query": "dashboard_data.collection_8.find({}, {\r\n  'time': '$MTConnectStreams.Header.@creationTime',\r\n  'Tormach-PCNC1100.Path.Events.Execution.#text': 1,\r\n  '_id': 0\r\n}).sort({RecordNumber: -1}).limit(120)"
    }
   ]
  }
 ]
}